$(document).ready(function(){
    $('.slider__body').slick({
        arrows:true,
        dots:true,
        adaptiveHeight:false,
        slidesToShow:1,
        slidesToScroll:1,
        speed:1000,
        easing:'linear',
        infinite:true,
        autoplay:true,
        autoplaySpeed:1500,
        pauseOnFocus:true,
        pauseOnDotsHover:false,
        pauseOnHover:false,
        draggable:true,
        swipe:true,
        touchThreshold:10,
        touchMove:true,
        waitForAnimate:true,
        centerMode:false,
        variableWidth:false,
        responsive:[
            {
                breakpoint:990,
                settings: {
                    dots:false,
                          }
            },
        ]
    });
});
